%.ll : %.cl Makefile stdlib.h
	./compile.sh $<

all: add.ll\
	add2.ll\
	cmp.ll\
	cmp_cvt.ll\
	complex_struct.ll\
	cycle.ll\
	extract.ll\
	function.ll\
	function_param.ll\
	get_global_id.ll\
	insert.ll\
	load_store.ll\
	loop.ll\
	loop2.ll\
	loop3.ll\
	loop4.ll\
	loop5.ll\
	select.ll\
	short.ll\
	shuffle.ll\
	simple_float4.ll\
	simple_float4_2.ll\
	simple_float4_3.ll\
	store.ll\
	struct.ll\
	struct2.ll\
	test_select.ll\
	undefined.ll\
	vector_constant.ll\
	void.ll

