include $(TOP)/Makefile.defs

all:: $(LIB)

$(OBJ): $(INC)

clean::
	rm -f $(OBJ)
	+cd $(TOP) && make -f Makefile.lib clean

$(LIB): $(OBJ)
	+cd $(TOP) && make -f Makefile.lib

list-obj:
	@echo $(OBJ)
