TOP=.
SUBDIRS=src/backend src/backend/gen src/backend/sim src/ir src/llvm src/sys src
include Makefile.defs

LIBS=-Wl,--no-undefined $(shell llvm-config-3.0 --libs) -ldl -lpthread

VERSION=0.0.1

all: $(LIB) $(LIBMAJOR) $(LIBBASE)

$(LIB): $(OBJ)
	$(CXX) $(CXXFLAGS) -shared -o $@ $(OBJ) $(LIBS)

$(LIBMAJOR): $(LIB)
	rm -f $@
	ln -s $(LIB) $@

$(LIBBASE): $(LIBMAJOR)
	rm -f $@
	ln -s $(LIBMAJOR) $@

clean:
	rm -f $(LIB) $(LIBMAJOR) $(LIBBASE)
