#! /bin/sh -e

CONVERT_HEADER=ocl_convert.h


exec >$CONVERT_HEADER.tmp
echo "// This file is autogenerated by gen_convert.sh."
echo "// Don't modify it manually."
./gen_convert.sh
exec >&2

mv $CONVERT_HEADER.tmp $CONVERT_HEADER
