//                 Family     Latency     SIMD16     SIMD8
DECL_GEN7_SCHEDULE(Label,           0,         0,        0)
DECL_GEN7_SCHEDULE(Unary,           20,        4,        2)
DECL_GEN7_SCHEDULE(Binary,          20,        4,        2)
DECL_GEN7_SCHEDULE(Ternary,         20,        4,        2)
DECL_GEN7_SCHEDULE(Compare,         20,        4,        2)
DECL_GEN7_SCHEDULE(Jump,            14,        1,        1)
DECL_GEN7_SCHEDULE(Eot,             20,        1,        1)
DECL_GEN7_SCHEDULE(NoOp,            20,        2,        2)
DECL_GEN7_SCHEDULE(Wait,            20,        2,        2)
DECL_GEN7_SCHEDULE(Math,            20,        4,        2)
DECL_GEN7_SCHEDULE(UntypedRead,     80,        1,        1)
DECL_GEN7_SCHEDULE(UntypedWrite,    80,        1,        1)
DECL_GEN7_SCHEDULE(ByteGather,      80,        1,        1)
DECL_GEN7_SCHEDULE(ByteScatter,     80,        1,        1)
DECL_GEN7_SCHEDULE(Region,          20,        1,        1)
DECL_GEN7_SCHEDULE(RGather,         30,        4,        2)
DECL_GEN7_SCHEDULE(OBRead,          80,        1,        1)
DECL_GEN7_SCHEDULE(OBWrite,         80,        1,        1)

